@menu1 = Menu.create(name: "Breakfast")
@menu2 = Menu.create(name: "Lunch")
@menu3 = Menu.create(name: "Dinner")
Item.create(menu_id: @menu1.id, name: "Eggs", price: 2.5 , description: "Two eggs, over easy")
Item.create(menu_id: @menu1.id, name: "Bacon", price: 1 , description: "Two strips of bacon, extra crispy")
Item.create(menu_id: @menu1.id, name: "Waffles", price: 3 , description: "Fluffy buttermilk waffles")
Item.create(menu_id: @menu2.id, name: "Turkey Sandwich", price: 5.25 , description: "Roast turkey sandwich with avocado")
Item.create(menu_id: @menu2.id, name: "Hamburger", price: 4.5 , description: "Hamburger on house-made bun. Add bacon for $1")
Item.create(menu_id: @menu2.id, name: "Soup of the day", price: 2.50 , description: "Chili")
Item.create(menu_id: @menu3.id, name: "Enchiladas", price: 7.5 , description: "Chef's special enchiladas")
Item.create(menu_id: @menu3.id, name: "Meatloaf", price: 8.25 , description: "Meatloaf served with mixed vegetables and mashed potatoes")
Item.create(menu_id: @menu3.id, name: "Steak", price: 12.99 , description: "8 oz sirloin cooked to order, served with mixed vegetables and mashed potatoes")